### ISSUE TITLE
Extreme decimal places for inputs on all shaders

### ISSUE THREAD

**Issue by GlintsMassiveDetails** [exeldro/obs-shaderfilter#13]
Most shaders have decimal spaces up to .000000 , making changing by the sliders too extreme and changing by scroll wheel too gradual. Its currently way too easy to accidentally remove the decimal and tell OBS you want a 8000000 strength shader when all you wanted was 8. Not sure if this an installation issue or not.

**Comment by exeldro** [comment]
converting the shaders to have a min and max values is work in progress at the moment

**Comment by exeldro** [comment]
the min and max values and step size is set for most shaders now
