### ISSUE TITLE
Show inline errors in the filter window (e.g. at the top of properties in red), if any

### ISSUE THREAD

**Issue by Destroy666x** [exeldro/obs-shaderfilter#19]
For easier debugging of new shaders.

**Comment by exeldro** [comment]
that is a good idea, let me see what is possible

**Comment by exeldro** [comment]
It is not possible yet, because OBS does not provide the error information to plugins yet.
I suggested changes to OBS to resolve this issue:
https://github.com/obsproject/obs-studio/pull/9649

**Comment by exeldro** [comment]
the plugin now shows errors and obs 30 and up will provide more error information
