### ISSUE TITLE
no version present in OBS Log

### ISSUE THREAD

**Issue by Landiie** [exeldro/obs-shaderfilter#26]
Noticed that there is no version listed in the log anywhere compared to your other plugins which do include the version in the log. Perhaps this is because it was a fork, and the original didn't have a version in the log? Would really appreciate this so I can check if users have an outdated version of shader filter for one of my projects 😊 it's caused some trouble already but nothing too bad

**Comment by exeldro** [comment]
I see a version in my log files, it is done here:
https://github.com/exeldro/obs-shaderfilter/blob/354a8a22dcb5f97f3a527df2448e09742ccc4cb3/obs-shaderfilter.c#L1342

it produces this line:
`09:08:55.751: [obs-shaderfilter] loaded version 2.1.3`

**Comment by Landiie** [comment]
you're right, my apologies, I must've missed it. Thanks!
