### ISSUE TITLE
User-Defined Shader not Showing

### ISSUE THREAD

**Issue by sidlulz** [exeldro/obs-shaderfilter#31]
I went ahead and downloaded the obs-shaderfilter today and the filter "user-defined shader" wont come up under my filters list. It is showing in logs and everything and I even double checked to make sure all files went to the correct destinations. It all looks good, but it still wont work. Wondering if it could be a conflict with another plugin or what. Any ideas?

Already did try uninstalling and reinstalling, as well as resetting OBS and my PC

**Comment by exeldro** [comment]
What filter list are you checking? It should be under effect filters. What version of OBS and the plugin? How is it showing in the log file?

**Comment by Blurbss** [comment]
@exeldro having same issue with latest plugin, running OBS 27.2.2

Is this version not supported?

**Comment by sidlulz** [comment]
I am checking under effect filters. I am on OBS 30.0.2 with Shaderfiler version 2.1.3.

This is a current log I have, which shows it on the list of plugins... 

https://obsproject.com/logs/HuEnc6vCZWpkY9wi

Not sure whats going on with it. I will say I also have this happening when I click view current log

![image](https://github.com/exeldro/obs-shaderfilter/assets/114529649/5e9dd3e0-d131-4c74-89a2-ad8226658fd8)

**Comment by exeldro** [comment]
@Blurbss obs-shaderfilter requires OBS 28 or higher

@sidlulz the provided log does not load any filter with id 'shader_filter', so the errors in the log file are not related to obs-shaderfilter 
I tested with OBS 30.0.2 and obs-shaderfilter 2.1.3 and got this option:
![image](https://github.com/exeldro/obs-shaderfilter/assets/5457024/aa841652-1dc2-4984-af4d-df8bf9d206a6)

**Comment by sidlulz** [comment]
Oh wow... I am completely sorry. This may be worth noting though

I have a secondary screen that I keep my OBS on that is in 4K (150% scale) and my primary is 1080 (100% scale). So there is a different scale for each screen. For some reason on my secondary screen the option just doesnt show up at the bottom there. Once I saw your reply I gave it a shot to try on the primary screen and it worked!

**Comment by exeldro** [comment]
Glad you got it working.
