### ISSUE TITLE
Off-scene transition video sources don't update or become visible for rendering when used

### ISSUE THREAD

**Issue by FishOfTheNorthStar** [exeldro/obs-shaderfilter#41]
When I would try to use video media sources as textures, I found they'd only work for me if they were in the current scene and visible.  For transitions this was a problem since I'd need many copies of  sources, also the videos should restart with the transition restarts.

I hacked a little fix in here locally that seems to be working for me.  

I'm struggling my way through github's learning curve.  Apologies if I'm making a mess of things.  Link below is to a commit that, for me, corrects the issue outlined.

**Comment by exeldro** [comment]
This looks like an issue that needs to be fixed, but I would do it an other way than you did it and also fix it for not transition shaders. I will link my solution to the issue here when I made it.

**Comment by exeldro** [comment]
I made a fix, you can see the changes [here](https://github.com/exeldro/obs-shaderfilter/commit/62ff679ee4b580b537b5b2cff5fa8ca10a60351f) and you can download a test build from the bottom of [this page](https://github.com/exeldro/obs-shaderfilter/actions/runs/7864452785).
Let me know if it fixes everything for you.

**Comment by FishOfTheNorthStar** [comment]
Thank you, I've tested your fix here locally and it's working great for what I'm doing.  I'm going to remove that temporary repo I forked now.   This issue is fully resolved for me.
