### ISSUE TITLE
[feature] Source Mirror

### ISSUE THREAD

**Issue by CortexReaver** [exeldro/obs-shaderfilter#42]
Source Mirror for different shaders like the one StreamFX does have.

**Comment by exeldro** [comment]
You want something like [Source Clone](https://obsproject.com/forum/resources/source-clone.1632/)?

**Comment by CortexReaver** [comment]
Oh, there is a separate plugin for that. And it was also made by you. Sorry for me being stupid, but I've tried to search a plugin with similar name on an OBS website and nothing came out... I guess I've just searched poorly.
Thx for the link.
