### ISSUE TITLE
unable to enter numbers larger than 1000 into uniforms

### ISSUE THREAD

**Issue by givowo** [exeldro/obs-shaderfilter#50]
for some reason, i cant enter in numbers >3 digits, for both float and int, into shader uniforms. using an autoclicker the biggest number is 1000, and entering a float such as 0.1000 doesnt allow you to delete the period to make it 1000

**Comment by givowo** [comment]
update: its numbers larger than 1000

**Comment by exeldro** [comment]
For each input there can be a minimum and maximum set, so it is different per shader. Is there a specific shader you have the issue with?

**Comment by givowo** [comment]
its one i've written myself, and [you can grab it here](https://gitlab.com/givowo/spiindraw/-/blob/main/SPINDA.hlsl?ref_type=heads). the specific uniforms that are causing issues are resolutionWidth and resolutionHeight. I made this before learning that theres a built in variable for screen resolution but being able to modify them makes the shader more customizable. For now the I'm entering values 1000x smaller then multiplying them by 1000 whenever theyre used (like 10 times throughout the code).

**Comment by exeldro** [comment]
There are no annotations on the uniforms in that shader. So there are no minimum and maximum set and it will get the default minimum and maximum.

**Comment by givowo** [comment]
oh! i had no idea there was a default minimum and maximum
