### ISSUE TITLE
Colorification of vectors.

### ISSUE THREAD

**Issue by DigiDigi** [exeldro/obs-shaderfilter#61]
Is there any way to turn off the transformation of float3 vectors into colors? Or the normalization?
I'm not sure what version this change happened (2.1.1ish? later?) I compiled 2.3.2 recently.
It mangles the values I set in float3 vectors and gives them color sliders.

**Comment by exeldro** [comment]
The way you get sliders for float3 is by setting annotation `string widget_type = "slider";`
By setting no widget_type you should get the color property.
https://github.com/exeldro/obs-shaderfilter/blob/aec1246d2028f0508cacfd33a5aec38206683fb5/obs-shaderfilter.c#L2155

**Comment by DigiDigi** [comment]
Ah so:
`uniform float3 testvec<
  string widget_type = "slider";
> = {0.08094445, -0.13050441,  0.11672107};`
That works.

Also I realized that non-uniform float3 don't get normalized, which also would have solved my problem.

Thanks for all the work on shaderfilter.
