### ISSUE TITLE
Filter are now stuck on scene

### ISSUE THREAD

**Issue by Josh65-2201** [exeldro/obs-shaderfilter#62]
I have just installed 2.3.2 on OBS 30.2.3. The filter were working then just stopped updating on the OBS output preview but the source filter preview show it correctly. I have edited and remove the filters and removed then added the video source again and the effect is still there.

**Comment by exeldro** [comment]
Can you provide an OBS log file and a video of the issue?

**Comment by Josh65-2201** [comment]
I'm not able to find any logs from OBS. I deleted the scene as I didn't before making the issue and that fixed it, so far hasn't happened again.

**Comment by Josh65-2201** [comment]
I found the issue to be the scene source I set keeping filters when removed
