### ISSUE TITLE
[Feature request] sample texture from another source

### ISSUE THREAD

**Issue by cgsdev0** [exeldro/obs-shaderfilter#65]
I'm curious how feasible it would be to have a parameterized `texture2d` that references another OBS source. I think this could be used to achieve some really interesting effects; particularly, I'm thinking this could be combined with something like [MiDaS](https://pytorch.org/hub/intelisl_midas_v2/) to sample a depth texture within a shader.

I would super appreciate if you could comment on the feasibility of a feature like this; I'm potentially be interested in implementing it myself, but I wanted to get your input first ^^

**Comment by exeldro** [comment]
That should work already. `uniform texture2d input_source` should give you a dropdown in the properties to select an other source. An example shader that uses that is the dynamic mask shader.
Is that what you're looking for?

**Comment by cgsdev0** [comment]
oh nice! you're way ahead of me 😅
